server {
    listen 80;
    listen [::]:80;
    server_name klad-v.ru www.klad-v.ru kladovaya.217-114-7-70.sslip.io;
    return 301 https://klad-v.ru$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name klad-v.ru www.klad-v.ru;

    ssl_certificate /etc/letsencrypt/live/klad-v.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/klad-v.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 12m;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 60s;
    }

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name kladovaya.217-114-7-70.sslip.io;

    ssl_certificate /etc/letsencrypt/live/kladovaya.217-114-7-70.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kladovaya.217-114-7-70.sslip.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://klad-v.ru$request_uri;
}
