server {
    listen 80;
    listen [::]:80;
    server_name oplatakladov.ru;

    root /var/www/oplatakladov;
    index index.html;

    location /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri /index.html;
    }

    location ~ /\. {
        deny all;
    }
}
